const MARKET_DATA = [
  {
    id: 1,
    title: "Hatchling",
    routeName: "market/hatchling",
    items: [
      {
        id: 1,
        name:
          "Mahogany Butter Pewter 100% Het Clown (Possible HGW And/or Fire)",
        genes: [
          "Butter",
          "Cinnamon",
          "Fire",
          "HGW",
          "Mahogany",
          "Pastel",
          "100% Het Clown",
        ],
        weight: "300",
        gender: "Male",
        diet: "Live Rat",
        birth: "2020",
        price: "45000",
        sellerName: "John Snow",
        location: "Kansas City, Missouri",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/48/97/4897873db76d007b646a877efffed1dc.jpg",
      },
      {
        id: 2,
        name: "OD Freeway",
        genes: ["Asphalt", "Orange Dream", "Yellow Belly"],
        weight: "1500",
        gender: "Male",
        diet: "Live Mouse",
        birth: "2019",
        price: "75000",
        sellerName: "Chris Hernan",
        location: "Holly, Michigan",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/2d/df/2ddf68269e33207e88c0267024054519.jpg",
      },
      {
        id: 3,
        name: "Mojave Nyala Pied",
        genes: ["Mojave", "Piebald"],
        weight: "100",
        gender: "Male",
        diet: "Live Mouse",
        birth: "2020",
        price: "18000",
        sellerName: "Ball Python Morphs. Co. Za",
        location: "Pretoria, Gauteng",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/d0/66/d0667a937035277b24e53f3940567158.jpg",
      },
      {
        id: 4,
        name: "Coral Glow Het Clown (Female Maker)",
        genes: ["Coral Glow", "100% Het Clown"],
        weight: "200",
        gender: "Male",
        diet: "Live Mouse",
        birth: "2020",
        price: "32000",
        sellerName: "Macfie Ball Pythons",
        location: "Boksburg, Gauteng",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/de/78/de78c6ba9442f19cec7b2de50caec93e.jpg",
      },
      {
        id: 5,
        name: "Axanthic Fire Spider Orange Dream",
        genes: ["Fire", "Axanthic (VPI)", "Spider", "Orange Dream"],
        weight: "100",
        gender: "Female",
        diet: "Live Mouse",
        birth: "2020",
        price: "12000",
        sellerName: "Court McGhee",
        location: "Pretoria, Gauteng",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/d2/d9/d2d999991a150e35077789fa8b46be2b.jpg",
      },
      {
        id: 6,
        name: "PB GHI Butter Yellow Belly",
        genes: ["Butter", "GHI", "Yellow Belly"],
        weight: "626",
        gender: "Male",
        diet: "Live Rat",
        birth: "2016",
        price: "7500",
        sellerName: "Prestige Morphs",
        location: "Johannesburg, Gauteng",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/01/da/01da3f61ed9dadf59ea61ea4f3211709.jpg",
      },
    ],
  },
  {
    id: 2,
    title: "Breeder",
    routeName: "market/breeder",
    items: [
      {
        id: 1,
        name:
          "Mahogany Butter Pewter 100% Het Clown (Possible HGW And/or Fire)",
        genes: [
          "Butter",
          "Cinnamon",
          "Fire",
          "HGW",
          "Mahogany",
          "Pastel",
          "100% Het Clown",
        ],
        weight: "300",
        gender: "Male",
        diet: "Live Rat",
        birth: "2020",
        price: "45000",
        sellerName: "John Snow",
        location: "Kansas City, Missouri",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/48/97/4897873db76d007b646a877efffed1dc.jpg",
      },
      {
        id: 2,
        name: "OD Freeway",
        genes: ["Asphalt", "Orange Dream", "Yellow Belly"],
        weight: "1500",
        gender: "Male",
        diet: "Live Mouse",
        birth: "2019",
        price: "75000",
        sellerName: "Chris Hernan",
        location: "Holly, Michigan",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/2d/df/2ddf68269e33207e88c0267024054519.jpg",
      },
      {
        id: 3,
        name: "Mojave Nyala Pied",
        genes: ["Mojave", "Piebald"],
        weight: "100",
        gender: "Male",
        diet: "Live Mouse",
        birth: "2020",
        price: "18000",
        sellerName: "Ball Python Morphs. Co. Za",
        location: "Pretoria, Gauteng",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/d0/66/d0667a937035277b24e53f3940567158.jpg",
      },
      {
        id: 4,
        name: "Coral Glow Het Clown (Female Maker)",
        genes: ["Coral Glow", "100% Het Clown"],
        weight: "200",
        gender: "Male",
        diet: "Live Mouse",
        birth: "2020",
        price: "32000",
        sellerName: "Macfie Ball Pythons",
        location: "Boksburg, Gauteng",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/de/78/de78c6ba9442f19cec7b2de50caec93e.jpg",
      },
      {
        id: 5,
        name: "Axanthic Fire Spider Orange Dream",
        genes: ["Fire", "Axanthic (VPI)", "Spider", "Orange Dream"],
        weight: "100",
        gender: "Female",
        diet: "Live Mouse",
        birth: "2020",
        price: "12000",
        sellerName: "Court McGhee",
        location: "Pretoria, Gauteng",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/d2/d9/d2d999991a150e35077789fa8b46be2b.jpg",
      },
      {
        id: 6,
        name: "PB GHI Butter Yellow Belly",
        genes: ["Butter", "GHI", "Yellow Belly"],
        weight: "626",
        gender: "Male",
        diet: "Live Rat",
        birth: "2016",
        price: "7500",
        sellerName: "Prestige Morphs",
        location: "Johannesburg, Gauteng",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/01/da/01da3f61ed9dadf59ea61ea4f3211709.jpg",
      },
    ],
  },
  {
    id: 3,
    title: "Female",
    routeName: "market/female",
    items: [
      {
        id: 1,
        name:
          "Mahogany Butter Pewter 100% Het Clown (Possible HGW And/or Fire)",
        genes: [
          "Butter",
          "Cinnamon",
          "Fire",
          "HGW",
          "Mahogany",
          "Pastel",
          "100% Het Clown",
        ],
        weight: "300",
        gender: "Male",
        diet: "Live Rat",
        birth: "2020",
        price: "45000",
        sellerName: "John Snow",
        location: "Kansas City, Missouri",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/48/97/4897873db76d007b646a877efffed1dc.jpg",
      },
      {
        id: 2,
        name: "OD Freeway",
        genes: ["Asphalt", "Orange Dream", "Yellow Belly"],
        weight: "1500",
        gender: "Male",
        diet: "Live Mouse",
        birth: "2019",
        price: "75000",
        sellerName: "Chris Hernan",
        location: "Holly, Michigan",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/2d/df/2ddf68269e33207e88c0267024054519.jpg",
      },
      {
        id: 3,
        name: "Mojave Nyala Pied",
        genes: ["Mojave", "Piebald"],
        weight: "100",
        gender: "Male",
        diet: "Live Mouse",
        birth: "2020",
        price: "18000",
        sellerName: "Ball Python Morphs. Co. Za",
        location: "Pretoria, Gauteng",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/d0/66/d0667a937035277b24e53f3940567158.jpg",
      },
      {
        id: 4,
        name: "Coral Glow Het Clown (Female Maker)",
        genes: ["Coral Glow", "100% Het Clown"],
        weight: "200",
        gender: "Male",
        diet: "Live Mouse",
        birth: "2020",
        price: "32000",
        sellerName: "Macfie Ball Pythons",
        location: "Boksburg, Gauteng",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/de/78/de78c6ba9442f19cec7b2de50caec93e.jpg",
      },
      {
        id: 5,
        name: "Axanthic Fire Spider Orange Dream",
        genes: ["Fire", "Axanthic (VPI)", "Spider", "Orange Dream"],
        weight: "100",
        gender: "Female",
        diet: "Live Mouse",
        birth: "2020",
        price: "12000",
        sellerName: "Court McGhee",
        location: "Pretoria, Gauteng",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/d2/d9/d2d999991a150e35077789fa8b46be2b.jpg",
      },
      {
        id: 6,
        name: "PB GHI Butter Yellow Belly",
        genes: ["Butter", "GHI", "Yellow Belly"],
        weight: "626",
        gender: "Male",
        diet: "Live Rat",
        birth: "2016",
        price: "7500",
        sellerName: "Prestige Morphs",
        location: "Johannesburg, Gauteng",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/01/da/01da3f61ed9dadf59ea61ea4f3211709.jpg",
      },
    ],
  },
  {
    id: 4,
    title: "Male",
    routeName: "market/male",
    items: [
      {
        id: 1,
        name:
          "Mahogany Butter Pewter 100% Het Clown (Possible HGW And/or Fire)",
        genes: [
          "Butter",
          "Cinnamon",
          "Fire",
          "HGW",
          "Mahogany",
          "Pastel",
          "100% Het Clown",
        ],
        weight: "300",
        gender: "Male",
        diet: "Live Rat",
        birth: "2020",
        price: "45000",
        sellerName: "John Snow",
        location: "Kansas City, Missouri",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/48/97/4897873db76d007b646a877efffed1dc.jpg",
      },
      {
        id: 2,
        name: "OD Freeway",
        genes: ["Asphalt", "Orange Dream", "Yellow Belly"],
        weight: "1500",
        gender: "Male",
        diet: "Live Mouse",
        birth: "2019",
        price: "75000",
        sellerName: "Chris Hernan",
        location: "Holly, Michigan",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/2d/df/2ddf68269e33207e88c0267024054519.jpg",
      },
      {
        id: 3,
        name: "Mojave Nyala Pied",
        genes: ["Mojave", "Piebald"],
        weight: "100",
        gender: "Male",
        diet: "Live Mouse",
        birth: "2020",
        price: "18000",
        sellerName: "Ball Python Morphs. Co. Za",
        location: "Pretoria, Gauteng",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/d0/66/d0667a937035277b24e53f3940567158.jpg",
      },
      {
        id: 4,
        name: "Coral Glow Het Clown (Female Maker)",
        genes: ["Coral Glow", "100% Het Clown"],
        weight: "200",
        gender: "Male",
        diet: "Live Mouse",
        birth: "2020",
        price: "32000",
        sellerName: "Macfie Ball Pythons",
        location: "Boksburg, Gauteng",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/de/78/de78c6ba9442f19cec7b2de50caec93e.jpg",
      },
      {
        id: 5,
        name: "Axanthic Fire Spider Orange Dream",
        genes: ["Fire", "Axanthic (VPI)", "Spider", "Orange Dream"],
        weight: "100",
        gender: "Female",
        diet: "Live Mouse",
        birth: "2020",
        price: "12000",
        sellerName: "Court McGhee",
        location: "Pretoria, Gauteng",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/d2/d9/d2d999991a150e35077789fa8b46be2b.jpg",
      },
      {
        id: 6,
        name: "PB GHI Butter Yellow Belly",
        genes: ["Butter", "GHI", "Yellow Belly"],
        weight: "626",
        gender: "Male",
        diet: "Live Rat",
        birth: "2016",
        price: "7500",
        sellerName: "Prestige Morphs",
        location: "Johannesburg, Gauteng",
        imageUrl:
          "https://morphmarket-media.s3.amazonaws.com/media/cache/01/da/01da3f61ed9dadf59ea61ea4f3211709.jpg",
      },
    ],
  },
];

export default MARKET_DATA;
